# Generated by Django 3.0.6 on 2020-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
