# Generated by Django 3.0.4 on 2020-05-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_auto_20200525_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='farmerdetails',
            options={'verbose_name_plural': 'FarmersInfo'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmers.Categories'),
        ),
    ]
