# Generated by Django 3.0.4 on 2020-05-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0015_auto_20200526_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
